spring.application.name=url_shortener
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/
spring.datasource.username=postgres
spring.datasource.password=Ani123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MongoDB connection
spring.data.mongodb.uri=mongodb://localhost:27017/urlshortenerdb

#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=urlshortenerdb
#spring.data.mongodb.username=MongoDB
#spring.data.mongodb.password=myPassword


#springdoc.api-docs.path= /api-docs
#swagger-ui.path= /swagger-ui.html
#swagger-ui.operationsSorter: method
#swagger-ui.tagsSorter: alpha
